modLoader = "javafml" #mandatory
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[dependencies."${mod_id}"]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "cofh_core"
mandatory = true
versionRange = "[11.0.0,11.1.0)"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "thermal"
mandatory = true
versionRange = "[11.0.3,11.1.0)"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "thermal_expansion"
mandatory = true
versionRange = "[11.0.1,11.1.0)"
ordering = "AFTER"
side = "BOTH"
